version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  couchdbsaver:
    image: iqtlabs/edgetech-couchdbsaver:latest
    network_mode: "host"
    build:
      context: ../edgetech-couchdb-saver/couchdbsaver
      dockerfile: ./Dockerfile
    environment:
      - TO_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - DEVICE_IP=${DEVICE_IP}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
