version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  couchdbsaver:
    image: iqtlabs/edgetech-couchdbsaver:latest
    network_mode: "host"
    build:
      context: ../edgetech-couchdb-saver/couchdbsaver
      dockerfile: ./Dockerfile
    environment:
      - SENSOR_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - TELEMETRY_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/telemetry/telemetry/string
      - AUDIO_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/Audio/edgetech-audio-recorder/string
      - COUCHDB_ERROR_TOPIC=/AISonobuoy/<HOSTNAME>/couchdbsaver/couchdb/errstring
      - MQTT_IP=mqtt
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SERVER_IP_ADDR=${COUCHDB_SERVER_IP_ADDR}
      - DEVICE_IP=${DEVICE_IP}
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
