version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-saver:
    image: iqtlabs/edgetech-couchdb-saver:latest
    build:
      context: ./couchdb-saver
      dockerfile: ./Dockerfile
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"